name: Build Flutter APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Flutter pub get
        run: flutter pub get

      - name: Add meta-data for embedding v2
        run: |
          sed -i '/<application/a\        <meta-data android:name="flutterEmbedding" android:value="2"/>' android/app/src/main/AndroidManifest.xml

      - name: Build APK
        run: flutter build apk --release

      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
