name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'

    - name: Install dependencies
      run: flutter pub get
      working-directory: ./CodeCHATAi   # <-- Burada, projenin bulunduğu klasör adı

    - name: Build APK
      run: flutter build apk
      working-directory: ./CodeCHATAi   # <-- Aynı şekilde build için de

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: codechatai-apk
        path: CodeCHATAi/build/app/outputs/flutter-apk/app-release.apk
